# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c90ea61d6933861095af5881326cd1277723c2dd33739812919802ae29c6676d75809029dc13cae5e11dd7d22232972dac28e039fd9b80d6cb783fe08a677c

test:
  secret_key_base: 9ea0d22853c6c1b4fa918ebf6f53af5357e5771a2da0e00c6068eb5ff9260dc2081030b7a5cd95b15d5aa8f32eb11fe22349370a0907aed45957031c136a84f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
